/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./../routes/__root";
import { Route as IndexImport } from "./../routes/index";
import { Route as InterestsIndexImport } from "./../routes/interests/index";
import { Route as InterestsCreateImport } from "./../routes/interests/create";
import { Route as InterestsIdImport } from "./../routes/interests/$id";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const InterestsIndexRoute = InterestsIndexImport.update({
  id: "/interests/",
  path: "/interests/",
  getParentRoute: () => rootRoute,
} as any);

const InterestsCreateRoute = InterestsCreateImport.update({
  id: "/interests/create",
  path: "/interests/create",
  getParentRoute: () => rootRoute,
} as any);

const InterestsIdRoute = InterestsIdImport.update({
  id: "/interests/$id",
  path: "/interests/$id",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/interests/$id": {
      id: "/interests/$id";
      path: "/interests/$id";
      fullPath: "/interests/$id";
      preLoaderRoute: typeof InterestsIdImport;
      parentRoute: typeof rootRoute;
    };
    "/interests/create": {
      id: "/interests/create";
      path: "/interests/create";
      fullPath: "/interests/create";
      preLoaderRoute: typeof InterestsCreateImport;
      parentRoute: typeof rootRoute;
    };
    "/interests/": {
      id: "/interests/";
      path: "/interests";
      fullPath: "/interests";
      preLoaderRoute: typeof InterestsIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/interests/$id": typeof InterestsIdRoute;
  "/interests/create": typeof InterestsCreateRoute;
  "/interests": typeof InterestsIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/interests/$id": typeof InterestsIdRoute;
  "/interests/create": typeof InterestsCreateRoute;
  "/interests": typeof InterestsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/interests/$id": typeof InterestsIdRoute;
  "/interests/create": typeof InterestsCreateRoute;
  "/interests/": typeof InterestsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/interests/$id" | "/interests/create" | "/interests";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/interests/$id" | "/interests/create" | "/interests";
  id: "__root__" | "/" | "/interests/$id" | "/interests/create" | "/interests/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  InterestsIdRoute: typeof InterestsIdRoute;
  InterestsCreateRoute: typeof InterestsCreateRoute;
  InterestsIndexRoute: typeof InterestsIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterestsIdRoute: InterestsIdRoute,
  InterestsCreateRoute: InterestsCreateRoute,
  InterestsIndexRoute: InterestsIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/interests/$id",
        "/interests/create",
        "/interests/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/interests/$id": {
      "filePath": "interests/$id.tsx"
    },
    "/interests/create": {
      "filePath": "interests/create.tsx"
    },
    "/interests/": {
      "filePath": "interests/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
