name: React CI - Typescript compilation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    name: Typescript compilation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        with:
          version: 10
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run typescript compilation
        run: pnpm check
