name: React CI - I18n checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    name: I18n checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        with:
          cwd: ./frontend
          version: 10
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run i18n sort
        run: pnpm i18n:sort
      - name: Check if files changed
        run: git diff --exit-code
      - name: Run i18n unused
        run: pnpm i18n:unused
