name: Create Sentry release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  sentry-release:
    name: Create Sentry release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Set version
        run: echo "COMMIT_GIT_SHA=$(git rev-parse --short=12 HEAD)" >> $GITHUB_ENV
      - name: Create backend Sentry release
        uses: getsentry/action-release@v1.11.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.BACKEND_SENTRY_PROJECT }}
        with:
          environment: production
          ignore_empty: true
          version: ${{ env.COMMIT_GIT_SHA }}
          working_directory: ./backend
      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run typescript compilation
        run: pnpm build-maps
      - name: Create frontend Sentry release
        uses: getsentry/action-release@v1.11.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.FRONTEND_SENTRY_PROJECT }}
        with:
          environment: production
          ignore_empty: true
          version: ${{ env.COMMIT_GIT_SHA }}
          sourcemaps: ./dist/assets
          working_directory: ./frontend
