name: CI - Spell Check with Typos

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4.2.2

      - name: Use custom config file
        uses: crate-ci/typos@v1.32.0
        with:
          config: ./typos.toml
